### ISSUE TITLE
Unable to build the app

### ISSUE THREAD

**Issue by Fr33maan** [Avaarie/app#1]
I have the following error:
```
Could not find a required file.
  Name: index.html
  Searched in: /home/freeman/dev/app/public
error Command failed with exit code 1.
```

I think you forget to commit some files. 
Could you add them again to the project ?

**Comment by Avaarie** [comment]
I did something, you can check if it works.

czw., 3 cze 2021 o 13:51 Fr33maan ***@***.***> napisał(a):

**Comment by Fr33maan** [comment]
it works, good job !
